// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mugnialby/go-microservices/auth-service/connections"
	"github.com/mugnialby/go-microservices/auth-service/handlers"
	"github.com/mugnialby/go-microservices/auth-service/proto/users"
	"github.com/mugnialby/go-microservices/auth-service/services"
	"github.com/mugnialby/go-microservices/auth-service/services/impl"
)

// Injectors from wire.go:

func InitAuthHandler() *handlers.AuthHandler {
	validationService := ProvideValidationService()
	userServiceClient := ProvideUserGrpcConnection()
	jwtService := ProvideJwtService()
	authHandler := ProvideAuthHandler(validationService, userServiceClient, jwtService)
	return authHandler
}

// wire.go:

/**
 * created by	: albym
 * created at	: 5 Jun 2024
 *
 * this class will generate providers for dependency injection
 */
func ProvideJwtService() services.JwtService {
	return servicesimpl.NewJwtService()
}

func ProvideValidationService() services.ValidationService {
	return servicesimpl.NewValidationService()
}

func ProvideUserGrpcConnection() users.UserServiceClient {
	return connections.NewUserConnection()
}

func ProvideAuthHandler(
	validationService services.ValidationService,
	userServiceClient users.UserServiceClient,
	jwtService services.JwtService,
) *handlers.AuthHandler {
	return handlers.NewAuthHandler(validationService, userServiceClient, jwtService)
}
