// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mugnialby/go-microservices/auth-service/handlers"
	"github.com/mugnialby/go-microservices/auth-service/services"
	"github.com/mugnialby/go-microservices/auth-service/services/impl"
)

// Injectors from wire.go:

func InitAuthHandler() *handlers.AuthHandler {
	authService := ProvideAuthService()
	authHandler := ProvideAuthHandler(authService)
	return authHandler
}

// wire.go:

/**
 * created by	: albym
 * created at	: 5 Jun 2024
 *
 * this class will generate providers for dependency injection
 */
func ProvideAuthService() services.AuthService {
	return servicesimpl.NewAuthService()
}

func ProvideAuthHandler(authService services.AuthService) *handlers.AuthHandler {
	return handlers.NewAuthHandler(authService)
}
