// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mugnialby/go-microservices/user-service/handlers"
	"github.com/mugnialby/go-microservices/user-service/proto/users"
	"github.com/mugnialby/go-microservices/user-service/repositories"
	"github.com/mugnialby/go-microservices/user-service/repositories/impl"
	"github.com/mugnialby/go-microservices/user-service/services"
	"github.com/mugnialby/go-microservices/user-service/services/grpcimpl"
	"github.com/mugnialby/go-microservices/user-service/services/impl"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserHandler(db *gorm.DB) *handlers.UserHandler {
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository)
	validationService := ProvideValidationService()
	userHandler := ProvideUserHandler(userService, validationService)
	return userHandler
}

func InitUserService(db *gorm.DB) services.UserService {
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository)
	return userService
}

func InitUserGrpcService(db *gorm.DB) users.UserServiceServer {
	userRepository := ProvideUserRepository(db)
	userService := ProvideUserService(userRepository)
	userServiceServer := ProvideUserGrpcService(userService)
	return userServiceServer
}

// wire.go:

/**
 * created by	: albym
 * created at	: 5 Jun 2024
 *
 * this class will generate providers for dependency injection
 */
func ProvideValidationService() services.ValidationService {
	return servicesimpl.NewValidationService()
}

func ProvideUserRepository(db *gorm.DB) repositories.UserRepository {
	return repositoriesimpl.NewUserRepository(db)
}

func ProvideUserService(userRepository repositories.UserRepository) services.UserService {
	return servicesimpl.NewUserService(userRepository)
}

func ProvideUserHandler(userService services.UserService, validationService services.ValidationService) *handlers.UserHandler {
	return handlers.NewUserHandler(userService, validationService)
}

func ProvideUserGrpcService(userService services.UserService) users.UserServiceServer {
	return grpcserviceimpl.NewUserServiceServer(userService)
}
